apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: respective-sheep-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-hub/respective-sheep-java-quarkus-gitops